// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdbggovatmceoobcldwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkYmdnb3ZhdG1jZW9vYmNsZHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNTMzMDksImV4cCI6MjA2NTkyOTMwOX0.6YCBsiiUR7j7RqD420rNDUmzPrUQjJOzWjwu5y9Dj2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);